#!/usr/bin/env node
// Check every plugin source for accessibility and open/update a GitHub issue
// listing any that return 404 or are otherwise unreachable. Designed to run
// weekly in CI so stale plugins are caught before users notice.

import { readFileSync, readdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");

const TOKEN = process.env.GITHUB_TOKEN;
if (!TOKEN) {
  console.error("GITHUB_TOKEN env var required");
  process.exit(1);
}

const GH_REPO = process.env.GITHUB_REPOSITORY; // owner/repo, set by Actions

const ghHeaders = {
  Authorization: `Bearer ${TOKEN}`,
  Accept: "application/vnd.github+json",
  "X-GitHub-Api-Version": "2022-11-28",
  "User-Agent": "agenthub-audit",
};

function extractGitHubRepo(source) {
  if (!source) return null;
  if (source.source === "github") return source.repo || null;
  // git-subdir and url sources all point at GitHub — extract owner/repo
  const url = source.url || "";
  const m = url.match(/github\.com[/:]([^/]+\/[^/]+?)(?:\.git)?(?:\/|$)/);
  return m ? m[1] : null;
}

const pluginsDir = resolve(REPO_ROOT, "plugins");
const plugins = readdirSync(pluginsDir)
  .filter((f) => f.endsWith(".json"))
  .map((f) => {
    const data = JSON.parse(readFileSync(resolve(pluginsDir, f), "utf-8"));
    return { file: f, ...data };
  });

async function checkGitHub(repo) {
  const res = await fetch(`https://api.github.com/repos/${repo}`, {
    headers: ghHeaders,
  });
  if (res.status === 404) return { ok: false, reason: "repo not found (404)" };
  if (res.status === 451)
    return { ok: false, reason: "unavailable for legal reasons (451)" };
  if (!res.ok) return { ok: false, reason: `HTTP ${res.status}` };
  const data = await res.json();
  return { ok: true, archived: Boolean(data.archived) };
}

async function checkNpm(pkg) {
  const res = await fetch(
    `https://registry.npmjs.org/${encodeURIComponent(pkg)}`,
    { method: "HEAD" },
  );
  if (res.status === 404) return { ok: false, reason: "package not found (404)" };
  if (!res.ok) return { ok: false, reason: `HTTP ${res.status}` };
  return { ok: true };
}

const failures = [];
const archived = [];

for (const plugin of plugins) {
  const { file, name, source } = plugin;

  let result;
  try {
    if (source?.source === "npm") {
      result = await checkNpm(source.package);
    } else {
      const repo = extractGitHubRepo(source);
      if (!repo) {
        failures.push({ file, name, reason: "could not resolve source repo" });
        continue;
      }
      result = await checkGitHub(repo);
    }
  } catch (e) {
    result = { ok: false, reason: e.message };
  }

  if (!result.ok) {
    failures.push({ file, name, reason: result.reason });
  } else if (result.archived) {
    archived.push({ file, name });
  }
}

console.log(
  `Audited ${plugins.length} plugins — ${failures.length} unreachable, ${archived.length} archived`,
);

if (failures.length === 0 && archived.length === 0) {
  console.log("All plugins OK.");
  process.exit(0);
}

// Build issue body
const date = new Date().toISOString().slice(0, 10);
let body = `Audited **${plugins.length} plugins** on ${date}.\n\n`;

if (failures.length > 0) {
  body += `### Unreachable (${failures.length})\n\n`;
  body += `These plugins should be removed — their source is gone or inaccessible:\n\n`;
  for (const { file, name, reason } of failures) {
    body += `- [ ] \`${file}\` (**${name}**) — ${reason}\n`;
  }
  body += "\n";
}

if (archived.length > 0) {
  body += `### Archived repos (${archived.length})\n\n`;
  body += `These plugins still exist but their source repo is archived. No action required unless you want to remove them.\n\n`;
  for (const { file, name } of archived) {
    body += `- \`${file}\` (**${name}**)\n`;
  }
  body += "\n";
}

body += `_Generated by the [weekly plugin audit](../../actions/workflows/plugin-audit.yml)._`;

const issueTitle = `Plugin audit (${date}): ${failures.length} unreachable`;

// Create or update the open audit issue
if (GH_REPO) {
  const [owner, repo] = GH_REPO.split("/");

  const listRes = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/issues?state=open&labels=plugin-audit&per_page=1`,
    { headers: ghHeaders },
  );
  const existing = await listRes.json();

  if (existing.length > 0) {
    await fetch(
      `https://api.github.com/repos/${owner}/${repo}/issues/${existing[0].number}`,
      {
        method: "PATCH",
        headers: { ...ghHeaders, "Content-Type": "application/json" },
        body: JSON.stringify({ title: issueTitle, body }),
      },
    );
    console.log(`Updated issue #${existing[0].number}`);
  } else {
    const res = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/issues`,
      {
        method: "POST",
        headers: { ...ghHeaders, "Content-Type": "application/json" },
        body: JSON.stringify({ title: issueTitle, body, labels: ["plugin-audit"] }),
      },
    );
    const issue = await res.json();
    console.log(`Created issue #${issue.number}`);
  }
}

if (failures.length > 0) process.exit(1);
